services:
  postgres:
    image: postgres:latest
    container_name: bootrain-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: boottrain
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/datas
  redis:
    image: redis:latest
    container_name: bootrain-redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

volumes:
  postgres-data:
